### ISSUE TITLE
Crash with high bitrates

### ISSUE THREAD

**Issue by jezhodges** [flavioribeiro/nginx-audio-track-for-hls-module#26]
I'm trying to extract audio tracks from several .ts files. This works fine for tracks with audio bitrates up until 128kbps. However, if for example, I try to extract a 320kbps audio track, nginx crashes. Any ideas?

**Comment by flavioribeiro** [comment]
Interesting. Can you give me access to your deploy or duplicate it in other place so I can try to find the problem?

**Comment by jezhodges** [comment]
I'm currently using this in connection with the nginx-rtmp module to enable HLS for a radio stream hence the use of this module for audio only tracks. Should I post up my nginx config?

**Comment by flavioribeiro** [comment]
sure, please give me a gist with your config

**Comment by jezhodges** [comment]
Here is the nginx.conf. https://gist.github.com/jezhodges/83f254adc391af4800d5

**Comment by jezhodges** [comment]
Not sure whether this helps but the error log shows this on crash.

2015/04/05 00:03:51 [alert] 3415#0: worker process 3416 exited on signal 6 (core dumped)
*** Error in `nginx: worker process': free(): invalid next size (normal): 0x000000000280c600 ***
2015/04/05 00:03:51 [alert] 3415#0: worker process 4143 exited on signal 6 (core dumped)
*** Error in `nginx: worker process': free(): invalid next size (fast): 0x0000000002865fe0 ***

**Comment by flavioribeiro** [comment]
@jezhodges still didn't have time to look deep on this. Can you try to reproduce building from fe3d94672b5d8d3b74782a60ad6d95c19ab451e3 commit?

**Comment by jezhodges** [comment]
Not a problem. Sorry for the lack of update, but I solved the crashing, by increasing the buffer size and audio chunk size. The problem has disappeared and have been streaming successfully for several days. Whether this is the correct way of doing this I don't know.

**Comment by flavioribeiro** [comment]
Awesome, could you show me your solution @jezhodges? Just for curiosity, where are you using this plugin?

**Comment by jezhodges** [comment]
Certainly. I am using this module to extract an audio track from a live nginx-rtmp stream, which provides a video track, which is not needed for a live radio stream.

My solution was:
- To update NGX_AAC_AUDIO_CHUNK_MAX_SIZE from 96100 to 288300 (3x increase)
- Change buffer_size from 1024 to 2048 (2x increase)

This seems to have prevented further crashes and has given a stable stream.

**Comment by flavioribeiro** [comment]
good. Do you mind sending a pull request?
