### ISSUE TITLE
av_register_all’ is deprecated

### ISSUE THREAD

**Issue by xvxieweilai** [flavioribeiro/nginx-audio-track-for-hls-module#37]
-o objs/addon/nginx-audio-track-for-hls-module/ngx_http_aac_module.o \
        ..//nginx-audio-track-for-hls-module/ngx_http_aac_module.c
..//nginx-audio-track-for-hls-module/ngx_http_aac_module.c: In function ‘ngx_http_aac_extract_audio’:
..//nginx-audio-track-for-hls-module/ngx_http_aac_module.c:159:5: error: ‘av_register_all’ is deprecated [-Werror=deprecated-declarations]
  159 |     av_register_all();
      |     ^~~~~~~~~~~~~~~
In file included from ..//nginx-audio-track-for-hls-module/ngx_http_aac_module.h:6,
                 from ..//nginx-audio-track-for-hls-module/ngx_http_aac_module.c:1:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:2050:6: note: declared here
 2050 | void av_register_all(void);
      |      ^~~~~~~~~~~~~~~
..//nginx-audio-track-for-hls-module/ngx_http_aac_module.c:218:33: error: ‘CODEC_FLAG_GLOBAL_HEADER’ undeclared (first use in this function); did you mean ‘AV_CODEC_FLAG_GLOBAL_HEADER’?
  218 |         out_codec_ctx->flags |= CODEC_FLAG_GLOBAL_HEADER;
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                 AV_CODEC_FLAG_GLOBAL_HEADER
..//nginx-audio-track-for-hls-module/ngx_http_aac_module.c:218:33: note: each undeclared identifier is reported only once for each function it appears in
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:1724: objs/addon/nginx-audio-track-for-hls-module/ngx_http_aac_module.o] Error 1
make[1]: Leaving directory '/home/xx/python/live/nginx-1.19.10'
make: *** [Makefile:10: build] Error 2

**Comment by flavioribeiro** [comment]
tag [0.3](https://github.com/flavioribeiro/nginx-audio-track-for-hls-module/releases/tag/0.3) should fix this issue.
